name = "Plagarism"
author = "donfran"
description = """
Don't feel like coding today, so I stole from a better ctf
"""
category = "web"
difficulty = "hard"
points = 200
flag = "DUCTF{Y0u_Kn0W_M4Ss_A5s1GnM3Nt_c890ne89c3}"

docker = true
port = 3001

