name = "Holy church of Jowett Part 1"
author = "Alex"
description = """
Come join the holy church of Jowett, high ranking cardinals get a flag
"""
category = "web"
difficulty = "easy"
points = 100
flag = "saint{h1s_h0lyness_w0uld_b3_pr0ud}"